version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - autoparking_network

  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 autoparking.wsgi"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    ports:
      - "80:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    networks:
      - autoparking_network

volumes:
  postgres_data:
  static_volume:

networks:
  autoparking_network: