name: Docker Image CI autoparking
    
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
  
  my-job:
    permissions:
      contents: read
      pull-requests: write
  
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag autoparking:$(date +%s)
